WhaleCrew/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path

from coins_app.views import *
from user_account_app.views import *
from home.views import IndexView, NewsListView, NewsPageView, AddArticleView
from footer_app.views import *




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='IndexPage'),
    path('login/', LoginView.as_view(), name='Login'),
    path('logout/', LogoutView.as_view(), name='Logout'),
    path('forgot_pass/', ForgotPass.as_view(), name='Forgot_Pass'),
    path('sing_up/', SingUp.as_view(), name='Sing_up'),
    path('contact/', Contact.as_view(), name='Contact'),
    path('news_list/', NewsListView.as_view(), name='NewsList'),
    path('news/<int:id>/', NewsPageView.as_view(), name='News_page'),
    path('add_article', AddArticleView.as_view(), name='AddArticle'),
    path('portfolio', PortfolioView.as_view(), name='PortfolioView'),
    path('<int:id>/', AddToFavoriteView.as_view(), name='AddTOFavorite'),
    path('reset/<slug:token>/', resetPasswordView, name='ResetPassword'),

    path('about_Us/', AboutUsView.as_view(), name='About_Us'),
    path('branding_guide/', BrandingGuideView.as_view(), name='Branding_Guide'),
    path('regulations/', RegulationsView.as_view(), name='Regulations'),
    path('get_candy/', GetCandyView.as_view(), name='GetCandy'),

    path('user_profile/', UserProfile.as_view(), name='UserProfile'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)

coins_app/models.py
from django.contrib.auth.models import User
from django.db import models


class CoinsInfo(models.Model):
    name = models.CharField(max_length=50, unique=True)
    symbol = models.CharField(max_length=20, unique=True)
    price = models.FloatField()
    usd_market_cap = models.FloatField()
    usd_24h_vol = models.FloatField()
    favourite = models.ManyToManyField(User, related_name="favourite", blank=True, default=False)

    def get_detail_url(self):
        """
        Return the url of Coin by ID
        """
        return f"{self.id}"

    def __str__(self):
        return f'{self.name} {self.symbol} {self.price}'


class Transaction(models.Model):
    profile = models.ForeignKey("user_account_app.Profile", on_delete=models.CASCADE)
    coin = models.ForeignKey('coins_app.CoinsInfo', on_delete=models.CASCADE)
    quantity = models.FloatField(default=0)
    price = models.FloatField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.profile}'

templates/Branding_Guide.html
{% extends 'base.html' %}
{% block content %}

    <br><br>
    <div class="text-center"><h1> Branding Guide </h1><br><br>

        Thank you for choosing to integrate WhaleCrew with your app.<br> We are extremely delighted!
        <br>
        <br>Below are some branding guidelines that you can use as reference. <br> We are continuously updating this
        documentation
        and would like to work closely with the community.
        <br><br>
        Feel free to contact us at k.odrobinski@gmail.com for questions and comments.<br><br>
        <h1> Logo: </h1><br><br>

        <img src="/static/logo.jpeg" alt="logo" width="320" height="240" class="d-inline-block"><br><br><br>

        <h1>Questions or Feedback?</h1>
        We are continuously improving this documentation.<br> Feel free to contact us at k.odrobinski@gmail.com for
        questions and comments.<br><br><br>
    </div>
{% endblock %}

templates/ForgotPassword.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="../static/css/user.css">

    <div class="wrapper fadeInDown">
        <div id="formContent">
            <h1>Forgot Password</h1>
            <br>
            Enter your email below and we'll send you a link to reset your password.
            <br>
            <br>

            <form method="post">
                {% csrf_token %}
                {{ form.email }}

                <input type="submit" class="fadeIn fourth" value="REMIND">

            </form>

        </div>
    </div>


{% endblock %}

templates/News_List.html
{% extends 'base.html' %}
{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                <!-- //--------------------------- ONE NEWS -------------------------// -->

                {% for obj in news %}
                    <div class="col-md-4 ">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top"
                                 data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
                                 alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;"
                                 src="/{{ obj.picture_file }}"
                                 data-holder-rendered="true">
                            <div class="card-body">
                                <p class="card-text">{{ obj.short_desc }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{{ obj.get_detail_url }}">
                                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        </a>
                                    </div>
                                    <small class="text-muted">{{ obj.created }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <!-- //--------------------------- PAGINATOR -------------------------// -->
            </div>

            {% if news.has_other_pages %}

                <ul class="pagination d-flex justify-content-center">

                    {% if news.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ news.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for i in news.paginator.page_range %}
                        {% if news.number == i %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if news.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ news.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>

            {% endif %}


        </div>
    </div>


{% endblock %}

templates/Sing_Up.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="../static/css/user.css">
<style>

input[type=password] {

background-color: #f6f6f6;

border: none;

color: #0d0d0d;

padding: 15px 32px;

text-align: center;

text-decoration: none;

display: inline-block;

font-size: 16px;

margin: 5px;

width: 85%;

border: 2px solid #f6f6f6;

-webkit-transition: all 0.5s ease-in-out;

-moz-transition: all 0.5s ease-in-out;

-ms-transition: all 0.5s ease-in-out;

-o-transition: all 0.5s ease-in-out;

transition: all 0.5s ease-in-out;

-webkit-border-radius: 5px 5px 5px 5px;

border-radius: 5px 5px 5px 5px;

}

input[type=password]:focus {

background-color: #fff;

border-bottom: 2px solid #5fbae9;

}

input[type=password]:placeholder {

color: #cccccc;

}

</style>


    <div class="wrapper fadeInDown">
        <div id="formContent">
            <h1>Create an Account</h1>
            <br>
            Already have an account? <a class="underlineHover" href="{% url 'Login' %}">Login</a>
            <br>
            <form method="post">
                {% csrf_token %}
                {% if error_user == 0 %}
                    <br>  <p style="color:red">!!! Username already exist !!!</p><br>
                {% endif %}
                {{ form.username }}
                {% if error_mail == 0 %}
                    <br><p style="color:red">!!! Email already exist !!!</p><br>
                {% endif %}
                {% if mail_error == 1 %}
                    <br><p style="color:red">!!! Wrong e-mail !!!</p><br>
                {% endif %}
                {{ form.email }}
                {{ form.password1 }}
                {{ form.password2 }}
                <input type="submit" class="fadeIn fourth" value="Log In">
            </form>

            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="{% url 'Forgot_Pass' %}">Forgot Password?</a>
            </div>

        </div>
    </div>


{% endblock %}

templates/add_news.html
{% extends 'base.html' %}
{% block content %}
    <div class="container contact-form">
        <div class="contact-image text-center">
            <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
        </div>

        <form method="post" enctype="multipart/form-data" action="{% url 'AddArticle' %}">

            {% csrf_token %}
            <center><h3>Create News</h3></center>
            {% if error_photo %}
            <h3 class="text-center"  style="color:red"> Error "add photo file" try to add other. </h3>
           {% endif %}
            {% if perm %}
            <h3 class="text-center"  style="color:red"> You don't have permission to add article </h3>
           {% endif %}
            <div class="row text-center">
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="text" name="Title" class="form-control" placeholder="Title" value=""/>
                    </div>
                    <div class="form-group">
                        <input type="text" name="ShortDesc" class="form-control" placeholder="Short Description"
                               value=""/>
                    </div>
                </div>


                <div class="form-group">
                    <br>
                    Wybierz zdjęcie:
                    <br>
                    <center><input type="file" name="photo2" class="form-control" id="customFile" style="width: 500px; "
                                                  accept="image/png, image/jpeg, image/jpg"  ></center>

                </div>


                <div class="form-group">
                    <br>
                    <textarea name="Text" class="form-control" placeholder="Article Text :"
                              style="width: 100%; height: 250px;"></textarea>
                </div>
                <br><br>
                {% if not perm %}
                    <h3 style="color:red"> You don't have permission to ADD ARTICLE ! </h3>
                {% endif %}
                <div class="form-group">
                    <input type="submit" name="btnSubmit" class="btnContact" value="Add Article"/>
                </div>
                <br>

            </div>


        </form>

    </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>WhaleCrew</title>
    <link rel="shortcut icon" href="/static/logo.jpeg"/>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/user.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/885fc84cf9.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0">
    <h1>WhaleCrew</h1>
</div>

<style>
    .bg-navigation {
        background-color: #003399;
    }
</style>

<!-- //--------------------------- Navigation Bar -------------------------// -->

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
        <!-- Brand/logo -->
        <div class="col-md-1">
            <ul class="nav navbar-nav float-left">
                <a class="navbar-brand" href="{% url 'IndexPage' %}">
                    <img src="/static/logo.jpeg" alt="logo" width="80" height="50" class="d-inline-block">
                </a>
            </ul>
        </div>
        <!-- Links -->
        <div class="col-md-9">
            <ul class="nav navbar-nav float-left">
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'IndexPage' %}">Cryptocurrency rate</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NewsList' %}">News</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'AddArticle' %}">Add News</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'PortfolioView' %}">Portfolio</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'Contact' %}">Contact</a>
                </li>
            </ul>
        </div>
    <div class="col-md-2">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'UserProfile' %}"><i class="far fa-user-circle"></i> Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Logout' %}"><i class="fas fa-door-open"></i> Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Login' %}"><i class="fas fa-sign-in-alt"></i> Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Sing_up' %}"><i class="fas fa-user-plus"></i> Sing Up</a>
                </li>


            {% endif %}
        </ul>
    </div>
    </div>
</nav>


<!-- //--------------------------- page content -------------------------// -->
{% block content %}{% endblock content %}
<!-- //--------------------------- page content end ---------------------// -->


<!-- //--------------------------- Footer -------------------------// -->


<!-- Footer -->
<footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4">
        <!-- Section: Social media -->
        <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/KarolMaciejOdrobinski/"
               role="button"
            ><i class="fab fa-facebook-f"></i
            ></a>


            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/karolmaciej/"
               role="button"
            ><i class="fab fa-instagram"></i
            ></a>

            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/karolodrobinski/"
               role="button"><i class="fab fa-linkedin-in"></i></a>

            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/Scarcfir" role="button"
            ><i class="fab fa-github"></i
            ></a>
        </section>
        <!-- Section: Social media -->

        <!-- Section: Text -->
        <section class="mb-4">
            <p>
                <b>Do you want to stay up to date with cryptocurrencies?</b>
                Subscribe to our free newsletter to receive the latest news, updates and reports from the cryptocurrency
                market.
            </p>
            {% if object_list == True %}
                <h1>Successful subscribe</h1>
            {% elif object_list == False %}
                <h1>Unsuccessful subscribe</h1>
            {% endif %}
        </section>
        <!-- Section: Text -->

        <!-- Section: Form -->
        <section class="">
            <form method="post" action="/">

                {% csrf_token %}
                <!--Grid row-->
                <div class="row d-flex justify-content-center">
                    <!--Grid column-->
                    <div class="col-auto">
                        <p class="pt-2">
                            <strong>Sign up for our newsletter</strong>
                        </p>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-5 col-12">
                        <!-- Email input -->
                        <div class="form-outline form-white mb-4">
                            <input type="email" name="EMAIL" id="EMAIL" class="form-control"/>
                            <label class="form-label" for="form5Example2">Email address</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-auto">
                        <!-- Submit button -->
                        <button type="submit" class="btn btn-outline-light mb-4">
                            Subscribe
                        </button>
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </form>


        </section>
        <!-- Section: Form -->

        <br>
        <!-- Section: Links -->
        <section class="">
            <!--Grid row-->
            <div class="row justify-content-center">

                <!--Grid column-->

                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">WhaleCrew</h5>
                    <br>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <p><a href="{% url 'About_Us' %}" class="text-white">About Us</a></p>
                        </li>
                        <li>
                            <p><a href="{% url 'Branding_Guide' %}" class="text-white">Branding Guide</a></p>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Regulations</h5>
                    <br>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <p><a href="{% url 'Regulations' %}" class="text-white">Regulations</a></p>
                        </li>
                        <li>
                            <p><a href="{% url 'GetCandy' %}" class="text-white">GetCandy</a></p>
                        </li>

                    </ul>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Kontakt</h5>
                    <br>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <p> Kontakt telefoniczny</p>
                        </li>
                        <li>
                            <p>pon. - pt.</p>
                        </li>
                        <li>
                            <p> od 8:00 do 16:00 </p>
                        </li>
                        <li>
                            <p> +48 884 302 451</p>
                        </li>
                        <li>
                            <p> mail: k.odrobinski@gmail.com </p>
                        </li>
                    </ul>
                </div>


                <!--Grid column-->
            </div>
            <!--Grid row-->
        </section>
        <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        &copy; Copyrights Company.com All rights reserved.

    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>

<script src="/static/js/bootstrap.min.js"></script>

</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="/static/css/user.css">
<div class="container contact-form">

            <div class="contact-image text-center">
                <img src="https://img.pngio.com/message-png-88-images-in-collection-p-259866-png-images-pngio-message-png-512_512.png" width="256" height="256" alt="rocket_contact"/>
            </div>

            <form method="post" action="{% url 'Contact' %}">
                {% csrf_token %}

                <h3>Drop Us a Message</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="../static/css/user.css">


<style>

input[type=password] {

background-color: #f6f6f6;

border: none;

color: #0d0d0d;

padding: 15px 32px;

text-align: center;

text-decoration: none;

display: inline-block;

font-size: 16px;

margin: 5px;

width: 85%;

border: 2px solid #f6f6f6;

-webkit-transition: all 0.5s ease-in-out;

-moz-transition: all 0.5s ease-in-out;

-ms-transition: all 0.5s ease-in-out;

-o-transition: all 0.5s ease-in-out;

transition: all 0.5s ease-in-out;

-webkit-border-radius: 5px 5px 5px 5px;

border-radius: 5px 5px 5px 5px;

}

input[type=password]:focus {

background-color: #fff;

border-bottom: 2px solid #5fbae9;

}

input[type=password]:placeholder {

color: #cccccc;

}

</style>


    <div class="wrapper fadeInDown">
        <div id="formContent">
            <h1>Log In</h1>
            <br>
            New to WhaleCrew? <a class="underlineHover" href="{% url 'Sing_up' %}">Create Account</a>
            <br>
            <form method="post" action="{% url 'Login' %}">
                {% csrf_token %}
                    {% if tekst == 1 %}
                       !!! Invalid Username or Password !!!
                    {% endif %}

                    {{ form.username }}
                    {{ form.password }}
                <input type="submit" class="fadeIn fourth" value="Log In">
            </form>

            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="{% url 'Forgot_Pass' %}">Forgot Password?</a>
            </div>

        </div>
    </div>


{% endblock %}

templates/portfolio.html
{% extends 'base.html' %}
{% block content %}

    <style>
        .table {
            margin: auto;
            width: 70% !important;
        }
    </style>
    <br><br>
    <div class="text-center"><h1> Your Portfolio </h1></div>



    <br>
    <table class="table table-bordered text-center">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Coin</th>
            <th scope="col">Ticker</th>
            <th scope="col">Actual Price</th>
            <th scope="col">Market Cap</th>
            <th scope="col">Quantity of Coin</th>
            <th scope="col">Holdings</th>
            <th scope="col">Balance</th>
            <th scope="col">Transaction</th>

        </tr>
        </thead>
        <tbody>

        {% for obj in paginator %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ obj.coin.name }}</td>
                <td>{{ obj.coin.symbol }}</td>
                <td>{{ obj.coin.price }} $</td>
                <td>{{ obj.coin.usd_market_cap }} mld $</td>
                <td>{{ obj.quantity }} </td>
                <td>{{ obj.current_value_of_holdings }} $</td>
                {% if obj.balance > 0 %}
                    <td><p style="color:green">{{ obj.balance }} $</p></td>
                {% elif obj.balance < 0 %}
                    <td><p style="color:red">{{ obj.balance }} $</p></td>
                {% else %}
                    <td>{{ obj.balance }} $</td>
                {% endif %}

                <td>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal"
                            data-bs-whatever="{{ obj.coin.name }}" data-bs-price="{{ obj.coin.price }}"
                            data-bs-idcoin="{{ obj.coin.id }}">Add Transaction
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">New transaction</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>

                                <div class="modal-body">

                                    <form method="post">
                                        {% csrf_token %}

                                        <div class="mb-3">
                                            <label for="price" class="col-form-label">Price per coin:</label>
                                            <input name="price_act" type="text" class="form-control" id="price"
                                                   value="0">
                                        </div>

                                        <div class="mb-3">
                                            <label for="amount" class="col-form-label">Quantity:</label>
                                            <input name="amount" type="text" class="form-control" id="quantity"
                                                   value="0">
                                        </div>
                                        <input type="hidden" id="id_coin" name="id_coin" value="{{ obj.coin.id }}">
                                        <input type="submit" id="submit-form" class="btnContact" value="Add"/>
                                    </form>

                                </div>

                                <div class="modal-footer">

                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <br>



    {% if paginator.has_other_pages %}

        <ul class="pagination d-flex justify-content-center">

            {% if paginator.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginator.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            {% endif %}

            {% for i in paginator.paginator.page_range %}
                {% if paginator.number == i %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if paginator.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ paginator.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            {% endif %}
        </ul>




    {% endif %}
    <br>
    <script>
        var exampleModal = document.getElementById('exampleModal')
        exampleModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            var button = event.relatedTarget
            // Extract info from data-bs-* attributes
            var recipient = button.getAttribute('data-bs-whatever')
            var price = button.getAttribute('data-bs-price')
            var id_coin = button.getAttribute('data-bs-idcoin')

            var modalTitle = exampleModal.querySelector('.modal-title')
            modalTitle.textContent = 'New transaction: ' + recipient
            var modalBodyInput = exampleModal.querySelectorAll('.modal-body input')
            modalBodyInput[1].value = price
            modalBodyInput[3].value = id_coin


        })</script>



{% endblock %}

templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ subject }}</title>
</head>
<body>
    Hi, please reset your password with: {{ link }}
</body>
</html>